# Generated by Django 6.1.1 on 2026-09-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='merchant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
