# Generated by Django 6.1.1 on 2026-09-05 17:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_account_userprofile_delete_phoneotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(default='UPI', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('BANK', 'Bank Account'), ('UPI', 'UPI Account'), ('CASH', 'Cash Vault'), ('CARD', 'Credit / Debit Card'), ('WALLET', 'Digital Wallet')], default='BANK', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Transaction', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('BILL', 'Bill Payment')], default='EXPENSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('45000.00'), max_digits=12),
        ),
    ]
