# Generated by Django 6.1.1 on 2026-09-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_payment_method_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.CharField(default='12:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='Primary Bank', max_length=100),
        ),
    ]
