import React, { useState } from 'react';
import { ArrowRight, Eye, EyeOff, LockKeyhole, ShieldCheck, Sparkles } from 'lucide-react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import api, { setTokens } from '../services/api';
import logoFull from '../assets/logo-full.png';

export default function Login() {
  const navigate=useNavigate(); const location=useLocation(); const {loginUser}=useAuth();
  const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [otp,setOtp]=useState(''); const [needsOtp,setNeedsOtp]=useState(false);
  const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const submit=async(e)=>{e.preventDefault();setLoading(true);setError('');try{const res=await api.post('/api/token/',{username:username.trim(),password,otp:otp.trim()||undefined});if(res.status===202||res.data?.two_factor_required){setNeedsOtp(true);setError(res.data?.detail||'Enter your authenticator code.');return}setTokens(res.data.access,res.data.refresh);loginUser(res.data.access,res.data.refresh);navigate(location.state?.from||'/',{replace:true})}catch(err){if(err.response?.data?.two_factor_required)setNeedsOtp(true);setError(err.response?.data?.detail||'Invalid username or password.')}finally{setLoading(false)}};
  return <div className="auth-page"><div className="auth-orb one"/><div className="auth-orb two"/><section className="auth-story"><img src={logoFull} alt="Smart Expense Tracker"/><div className="auth-story-copy"><div className="eyebrow">SMART MONEY • LESS NOISE</div><h1>Know exactly where your money is going.</h1><p>Transactions, OCR receipts, analytics, bills, automation and goals — one secure workspace.</p><div className="auth-points"><div><Sparkles size={18}/><span>Automatic receipt capture</span></div><div><ShieldCheck size={18}/><span>User-isolated secure data</span></div><div><LockKeyhole size={18}/><span>JWT + optional 2FA</span></div></div></div></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><div className="auth-mobile-logo"><img src={logoFull} alt="Smart Expense Tracker"/></div><span className="micro-label">WELCOME BACK</span><h2>Sign in to your workspace</h2><p>Continue from exactly where you left your finances.</p>{error&&<div className={`alert ${needsOtp?'success':'error'}`}>{error}</div>}<label><span>Username or email</span><input autoFocus required value={username} onChange={e=>setUsername(e.target.value)} placeholder="Enter username or email" autoComplete="username"/></label><label><span>Password</span><div className="password-field"><input required type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" autoComplete="current-password"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{needsOtp&&<label><span>Authenticator or recovery code</span><input required maxLength="16" value={otp} onChange={e=>setOtp(e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g,'').slice(0,16))} placeholder="6-digit code or recovery code" autoComplete="one-time-code"/></label>}<button className="button primary full auth-submit" disabled={loading}>{loading?'Signing in…':<>Sign in <ArrowRight size={18}/></>}</button><div className="auth-switch">New to Smart Expense? <Link to="/register">Create an account</Link></div><div className="auth-secure"><ShieldCheck size={15}/> Secure personal finance workspace</div></form></section></div>;
}

