import React, { useState } from 'react';
import { ArrowRight, Eye, EyeOff, KeyRound, LockKeyhole, ShieldCheck, Sparkles } from 'lucide-react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import api, { setTokens } from '../services/api';
import logoFull from '../assets/logo-full.png';

export default function Login() {
  const navigate=useNavigate(); const location=useLocation(); const {loginUser}=useAuth();
  const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [otp,setOtp]=useState(''); const [needsOtp,setNeedsOtp]=useState(false);
  const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [resetOpen,setResetOpen]=useState(false);
  const submit=async(e)=>{e.preventDefault();setLoading(true);setError('');try{const res=await api.post('/api/token/',{username:username.trim(),password,otp:otp.trim()||undefined});if(res.status===202||res.data?.two_factor_required){setNeedsOtp(true);setError(res.data?.detail||'Enter your authenticator code.');return}setTokens(res.data.access,res.data.refresh);loginUser(res.data.access,res.data.refresh);navigate(location.state?.from||'/',{replace:true})}catch(err){if(err.response?.data?.two_factor_required)setNeedsOtp(true);setError(err.response?.data?.detail||'Invalid username or password.')}finally{setLoading(false)}};
  return <div className="auth-page"><div className="auth-orb one"/><div className="auth-orb two"/><section className="auth-story"><img src={logoFull} alt="Smart Expense Tracker"/><div className="auth-story-copy"><div className="eyebrow">SMART MONEY • LESS NOISE</div><h1>Know exactly where your money is going.</h1><p>Transactions, OCR receipts, analytics, bills, automation and goals — one secure workspace.</p><div className="auth-points"><div><Sparkles size={18}/><span>Automatic receipt capture</span></div><div><ShieldCheck size={18}/><span>User-isolated secure data</span></div><div><LockKeyhole size={18}/><span>JWT + optional 2FA</span></div></div></div></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><div className="auth-mobile-logo"><img src={logoFull} alt="Smart Expense Tracker"/></div><span className="micro-label">WELCOME BACK</span><h2>Sign in to your workspace</h2><p>Continue from exactly where you left your finances.</p>{error&&<div className={`alert ${needsOtp?'success':'error'}`}>{error}</div>}<label><span>Username or email</span><input autoFocus required value={username} onChange={e=>setUsername(e.target.value)} placeholder="Enter username or email" autoComplete="username"/></label><label><span>Password</span><div className="password-field"><input required type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" autoComplete="current-password"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{needsOtp&&<label><span>Authenticator code</span><input required inputMode="numeric" maxLength="6" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6-digit code" autoComplete="one-time-code"/></label>}<button className="button primary full auth-submit" disabled={loading}>{loading?'Signing in…':<>Sign in <ArrowRight size={18}/></>}</button><button type="button" className="text-button auth-forgot" onClick={()=>setResetOpen(true)}><KeyRound size={14}/> Forgot password?</button><div className="auth-switch">New to Smart Expense? <Link to="/register">Create an account</Link></div><div className="auth-secure"><ShieldCheck size={15}/> Secure personal finance workspace</div></form></section>{resetOpen&&<PasswordResetModal onClose={()=>setResetOpen(false)}/>}</div>;
}

function PasswordResetModal({onClose}){const[email,setEmail]=useState('');const[code,setCode]=useState('');const[password,setPassword]=useState('');const[step,setStep]=useState(1);const[message,setMessage]=useState('');const[error,setError]=useState('');const request=async e=>{e.preventDefault();setError('');try{const r=await api.post('/api/v3/password-reset/request/',{email});setMessage(r.data?.message||'Reset code sent');setStep(2)}catch(err){setError(err.response?.data?.error||'Unable to request reset')}};const confirm=async e=>{e.preventDefault();setError('');try{const r=await api.post('/api/v3/password-reset/confirm/',{email,code,new_password:password});setMessage(r.data?.message||'Password reset');setTimeout(onClose,900)}catch(err){setError(err.response?.data?.error||'Unable to reset password')}};return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal-card reset-card" onMouseDown={e=>e.stopPropagation()} onSubmit={step===1?request:confirm}><div className="modal-head"><div><span>ACCOUNT RECOVERY</span><h2>Reset password</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div>{message&&<div className="alert success">{message}</div>}{error&&<div className="alert error">{error}</div>}<label><span>Email</span><input required type="email" value={email} disabled={step===2} onChange={e=>setEmail(e.target.value)}/></label>{step===2&&<><label><span>Reset code</span><input required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric"/></label><label><span>New password</span><input required minLength="8" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label></>}<button className="button primary full">{step===1?'Send reset code':'Reset password'}</button></form></div>}
