import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarClock, CheckCircle2, CircleDollarSign, HandCoins, Plus, Target, Trash2, X } from 'lucide-react';
import api from '../services/api';
import { EmptyState, PageHeader, Progress, Surface, money } from '../components/Ui';
import { useFinance } from '../context/FinanceContext';

const today = () => new Date().toISOString().slice(0,10);

export default function MoneyHub() {
  const { profile, notify, refresh: refreshBase } = useFinance();
  const symbol=profile?.currency||'₹';
  const [tab,setTab]=useState('debts');
  const [debts,setDebts]=useState([]); const [bills,setBills]=useState([]); const [goals,setGoals]=useState([]);
  const [loading,setLoading]=useState(true); const [modal,setModal]=useState(null); const [saving,setSaving]=useState(false);

  const load=useCallback(async()=>{setLoading(true);try{const [d,b,g]=await Promise.all([api.get('/api/money-debts/'),api.get('/api/bills/'),api.get('/api/savings-goals/')]);setDebts(d.data||[]);setBills(b.data||[]);setGoals(g.data||[]);}catch(err){notify(err.response?.data?.error||'Unable to load Money Hub','error');}finally{setLoading(false)}},[notify]);
  useEffect(()=>{load()},[load]);

  const totals=useMemo(()=>({
    owe:debts.filter(x=>x.direction==='BORROWED'&&x.status!=='PAID').reduce((s,x)=>s+Number(x.remaining_amount||0),0),
    receivable:debts.filter(x=>x.direction==='LENT'&&x.status!=='PAID').reduce((s,x)=>s+Number(x.remaining_amount||0),0),
    bills:bills.filter(x=>!x.is_paid).reduce((s,x)=>s+Number(x.amount||0),0),
    savings:goals.reduce((s,x)=>s+Number(x.current_amount||0),0),
  }),[debts,bills,goals]);

  const saveDebt=async(data)=>{setSaving(true);try{const payload={...data}; if(!payload.due_date) delete payload.due_date; await api.post('/api/money-debts/',payload);notify('Money record added');setModal(null);await load();await refreshBase();}catch(err){notify(err.response?.data?.error||'Unable to add money record','error')}finally{setSaving(false)}};
  const saveBill=async(data)=>{setSaving(true);try{await api.post('/api/bills/',data);notify('Bill added');setModal(null);await load();await refreshBase();}catch(err){notify(err.response?.data?.error||'Unable to add bill','error')}finally{setSaving(false)}};
  const saveGoal=async(data)=>{setSaving(true);try{const payload={...data}; if(!payload.target_date) delete payload.target_date; await api.post('/api/savings-goals/',payload);notify('Savings goal added');setModal(null);await load();await refreshBase();}catch(err){notify(err.response?.data?.error||'Unable to add goal','error')}finally{setSaving(false)}};
  const payDebt=async(debt)=>{const raw=window.prompt(`Payment amount (remaining ${money(debt.remaining_amount,symbol)})`);if(!raw)return;try{await api.post(`/api/money-debts/${debt.id}/payments/`,{amount:raw,payment_date:today()});notify('Repayment recorded');await load();await refreshBase();}catch(err){notify(err.response?.data?.error||'Unable to record payment','error')}};
  const toggleBill=async(bill)=>{try{await api.patch(`/api/bills/${bill.id}/`,{is_paid:!bill.is_paid});notify(bill.is_paid?'Bill marked unpaid':'Bill marked paid');await load();await refreshBase();}catch{notify('Unable to update bill','error')}};
  const updateGoal=async(goal)=>{const raw=window.prompt(`Current saved amount for ${goal.name}`,goal.current_amount);if(raw===null)return;try{await api.patch(`/api/savings-goals/${goal.id}/`,{current_amount:raw});notify('Goal updated');await load();await refreshBase();}catch(err){notify(err.response?.data?.current_amount?.[0]||'Unable to update goal','error')}};
  const remove=async(kind,id)=>{if(!window.confirm('Delete this record?'))return;const path=kind==='debt'?'money-debts':kind==='bill'?'bills':'savings-goals';try{await api.delete(`/api/${path}/${id}/`);notify('Record deleted');await load();await refreshBase();}catch{notify('Unable to delete record','error')}};

  return <div className="page-stack">
    <PageHeader eyebrow="MONEY HUB" title="Commitments & goals" description="Track borrowed/lent money, upcoming bills and savings goals without mixing them into your daily ledger." actions={<button className="button primary" onClick={()=>setModal(tab==='debts'?'debt':tab==='bills'?'bill':'goal')}><Plus size={18}/> Add {tab==='debts'?'record':tab==='bills'?'bill':'goal'}</button>} />
    <section className="money-summary"><div><span>You owe</span><strong>{money(totals.owe,symbol)}</strong></div><div><span>Owed to you</span><strong>{money(totals.receivable,symbol)}</strong></div><div><span>Unpaid bills</span><strong>{money(totals.bills,symbol)}</strong></div><div><span>Saved toward goals</span><strong>{money(totals.savings,symbol)}</strong></div></section>
    <div className="segmented"><button className={tab==='debts'?'active':''} onClick={()=>setTab('debts')}><HandCoins size={17}/> Borrow / Lend</button><button className={tab==='bills'?'active':''} onClick={()=>setTab('bills')}><CalendarClock size={17}/> Bills</button><button className={tab==='goals'?'active':''} onClick={()=>setTab('goals')}><Target size={17}/> Savings goals</button></div>

    <Surface>
      {loading ? <div className="loading-state">Loading Money Hub…</div> : tab==='debts' ? (debts.length ? <div className="money-list">{debts.map((x)=><div className="money-row" key={x.id}><div className={`money-badge ${x.direction==='LENT'?'lent':'borrowed'}`}><HandCoins size={19}/></div><div className="money-main"><strong>{x.person_name}</strong><span>{x.direction==='LENT'?'Owes you':'You owe'} • {x.purpose||'No purpose'} • {x.due_date?`Due ${x.due_date}`:'No due date'}</span><Progress value={(Number(x.amount_paid||0)/Number(x.amount||1))*100}/></div><div className="money-amount"><strong>{money(x.remaining_amount,symbol)}</strong><span>{x.status}</span></div>{x.status!=='PAID'&&<button className="mini-button" onClick={()=>payDebt(x)}>Record payment</button>}<button className="icon-button danger" onClick={()=>remove('debt',x.id)}><Trash2 size={16}/></button></div>)}</div> : <EmptyState title="No borrow/lend records" description="Add money you borrowed or lent and track repayments here."/>) : tab==='bills' ? (bills.length ? <div className="money-list">{bills.map((x)=><div className="money-row" key={x.id}><button className={`bill-check ${x.is_paid?'paid':''}`} onClick={()=>toggleBill(x)}><CheckCircle2 size={21}/></button><div className="money-main"><strong>{x.title}</strong><span>{x.category} • Due {x.due_date} {x.is_recurring?'• Recurring':''}</span></div><div className="money-amount"><strong>{money(x.amount,symbol)}</strong><span>{x.is_paid?'PAID':'PENDING'}</span></div><button className="icon-button danger" onClick={()=>remove('bill',x.id)}><Trash2 size={16}/></button></div>)}</div> : <EmptyState title="No bills tracked" description="Add upcoming bills and mark them paid when completed."/>) : (goals.length ? <div className="goal-grid">{goals.map((x)=><div className="goal-card" key={x.id}><div className="goal-top"><div className="goal-icon">{x.icon||'🎯'}</div><button className="icon-button danger" onClick={()=>remove('goal',x.id)}><Trash2 size={15}/></button></div><strong>{x.name}</strong><span>{money(x.current_amount,symbol)} of {money(x.target_amount,symbol)}</span><Progress value={x.progress_percent}/><div className="goal-footer"><small>{x.progress_percent}% complete {x.target_date?`• ${x.target_date}`:''}</small><button className="text-button" onClick={()=>updateGoal(x)}>Update saved</button></div></div>)}</div> : <EmptyState title="No savings goals" description="Create a target and update your saved amount as you progress."/>)}
    </Surface>
    {modal && <MoneyModal kind={modal} saving={saving} onClose={()=>setModal(null)} onDebt={saveDebt} onBill={saveBill} onGoal={saveGoal}/>} 
  </div>;
}

function MoneyModal({kind,saving,onClose,onDebt,onBill,onGoal}) {
  const [form,setForm]=useState(kind==='debt'?{direction:'BORROWED',person_name:'',amount:'',transaction_date:today(),due_date:'',purpose:'',notes:''}:kind==='bill'?{title:'',amount:'',due_date:today(),category:'Bills & Utilities',is_recurring:true}:{name:'',target_amount:'',current_amount:'0',target_date:'',icon:'🎯'});
  const set=(k,v)=>setForm(p=>({...p,[k]:v}));
  const submit=(e)=>{e.preventDefault(); if(kind==='debt')onDebt(form); else if(kind==='bill')onBill(form); else onGoal(form)};
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal-card" onSubmit={submit} onMouseDown={(e)=>e.stopPropagation()}><div className="modal-head"><div><span>{kind==='debt'?'BORROW / LEND':kind==='bill'?'NEW BILL':'SAVINGS TARGET'}</span><h2>{kind==='debt'?'Add money record':kind==='bill'?'Add bill':'Create savings goal'}</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={19}/></button></div>{kind==='debt'?<><label><span>Direction</span><select value={form.direction} onChange={e=>set('direction',e.target.value)}><option value="BORROWED">I borrowed — I owe</option><option value="LENT">I lent — owed to me</option></select></label><label><span>Person</span><input required value={form.person_name} onChange={e=>set('person_name',e.target.value)} placeholder="Name"/></label><label><span>Amount</span><input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>set('amount',e.target.value)}/></label><div className="form-grid two"><label><span>Date</span><input type="date" value={form.transaction_date} onChange={e=>set('transaction_date',e.target.value)}/></label><label><span>Due date</span><input type="date" value={form.due_date} onChange={e=>set('due_date',e.target.value)}/></label></div><label><span>Purpose</span><input value={form.purpose} onChange={e=>set('purpose',e.target.value)} placeholder="Trip, emergency, loan…"/></label></>:kind==='bill'?<><label><span>Bill name</span><input required value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Internet, rent, EMI…"/></label><div className="form-grid two"><label><span>Amount</span><input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>set('amount',e.target.value)}/></label><label><span>Due date</span><input required type="date" value={form.due_date} onChange={e=>set('due_date',e.target.value)}/></label></div><label><span>Category</span><input value={form.category} onChange={e=>set('category',e.target.value)}/></label></>:<><label><span>Goal name</span><input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Emergency fund, laptop, trip…"/></label><div className="form-grid two"><label><span>Target</span><input required type="number" min="0.01" step="0.01" value={form.target_amount} onChange={e=>set('target_amount',e.target.value)}/></label><label><span>Already saved</span><input type="number" min="0" step="0.01" value={form.current_amount} onChange={e=>set('current_amount',e.target.value)}/></label></div><label><span>Target date</span><input type="date" value={form.target_date} onChange={e=>set('target_date',e.target.value)}/></label></>}<button className="button primary full" disabled={saving}><CircleDollarSign size={18}/>{saving?'Saving…':'Save record'}</button></form></div>
}
