import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRightLeft, CalendarDays, CreditCard, Download, FolderUp, Plus, Repeat2, Tags, Trash2, Upload, WalletCards } from 'lucide-react';
import api from '../services/api';
import { EmptyState, PageHeader, Progress, Surface, money } from '../components/Ui';
import { useFinance } from '../context/FinanceContext';

const today = () => new Date().toISOString().slice(0,10);
const monthNow = () => new Date().toISOString().slice(0,7);
const defaultCategories = ['Food & Dining','Groceries','Shopping','Travel & Fuel','Health','Entertainment','Education','Bills & Utilities','Rent','Subscription','Loan EMI','Salary','Freelance','General'];

export default function Planner(){
  const { accounts, profile, notify, refresh } = useFinance();
  const symbol = profile?.currency || '₹';
  const [tab,setTab]=useState('budgets');
  const [budgets,setBudgets]=useState([]); const [recurring,setRecurring]=useState([]); const [transfers,setTransfers]=useState([]); const [cards,setCards]=useState([]); const [categories,setCategories]=useState([]);
  const [calendar,setCalendar]=useState({transactions:[],bills:[],transfers:[],recurring:[]}); const [month,setMonth]=useState(monthNow());
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const backupInput=useRef(null); const csvInput=useRef(null);

  const load=useCallback(async()=>{setLoading(true);try{const [b,r,t,c,cat,cal]=await Promise.all([
    api.get('/api/v3/category-budgets/'),api.get('/api/v3/recurring/'),api.get('/api/v3/transfers/'),api.get('/api/v3/credit-cards/'),api.get('/api/v3/categories/'),api.get(`/api/v3/calendar/?month=${month}`)
  ]);setBudgets(b.data||[]);setRecurring(r.data||[]);setTransfers(t.data||[]);setCards(c.data||[]);setCategories(cat.data||[]);setCalendar(cal.data||{});}catch(err){notify(err.response?.data?.error||'Unable to load planner','error')}finally{setLoading(false)}},[month,notify]);
  useEffect(()=>{load()},[load]);

  const remove=async(path,id)=>{if(!window.confirm('Delete this item?'))return;try{await api.delete(`/api/v3/${path}/${id}/`);notify('Deleted');await load();await refresh()}catch{notify('Unable to delete','error')}};
  const createBudget=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{await api.post('/api/v3/category-budgets/',{category:f.get('category'),amount:f.get('amount')});e.currentTarget.reset();notify('Category budget added');await load()}catch(err){notify(err.response?.data?.category?.[0]||err.response?.data?.non_field_errors?.[0]||'Unable to add budget','error')}finally{setSaving(false)}};
  const createRecurring=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{await api.post('/api/v3/recurring/',{title:f.get('title'),amount:f.get('amount'),transaction_type:f.get('transaction_type'),category:f.get('category'),account:f.get('account')||null,payment_method:f.get('payment_method'),frequency:f.get('frequency'),interval:Number(f.get('interval')||1),next_run:f.get('next_run'),notes:f.get('notes')||''});e.currentTarget.reset();notify('Recurring rule added');await load()}catch(err){notify(err.response?.data?.detail||'Unable to add recurring rule','error')}finally{setSaving(false)}};
  const createTransfer=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{await api.post('/api/v3/transfers/',{from_account:f.get('from_account'),to_account:f.get('to_account'),amount:f.get('amount'),date:f.get('date'),notes:f.get('notes')||''});e.currentTarget.reset();notify('Transfer completed');await load();await refresh()}catch(err){notify(err.response?.data?.non_field_errors?.[0]||err.response?.data?.error||'Unable to transfer','error')}finally{setSaving(false)}};
  const createCard=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{await api.post('/api/v3/credit-cards/',{name:f.get('name'),last4:f.get('last4'),credit_limit:f.get('credit_limit'),outstanding:f.get('outstanding')||0,statement_day:Number(f.get('statement_day')),due_day:Number(f.get('due_day')),linked_account:f.get('linked_account')||null});e.currentTarget.reset();notify('Credit card added');await load()}catch(err){notify(err.response?.data?.last4?.[0]||'Unable to add card','error')}finally{setSaving(false)}};
  const createCategory=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{await api.post('/api/v3/categories/',{name:f.get('name'),category_type:f.get('category_type'),color:f.get('color')||'#0A84FF',icon:'Tag'});e.currentTarget.reset();notify('Category added');await load()}catch(err){notify(err.response?.data?.name?.[0]||'Unable to add category','error')}finally{setSaving(false)}};
  const cardActivity=async(card,type)=>{const amount=window.prompt(`${type==='PURCHASE'?'Purchase':'Payment'} amount`);if(!amount)return;let payment_account=null;if(type==='PAYMENT'&&accounts.length){payment_account=window.prompt(`Payment account ID: ${accounts.map(a=>`${a.id}=${a.name}`).join(', ')}`,accounts[0].id);if(!payment_account)return;}try{await api.post(`/api/v3/credit-cards/${card.id}/activity/`,{activity_type:type,amount,date:today(),payment_account});notify(type==='PURCHASE'?'Purchase recorded':'Payment recorded');await load();await refresh()}catch(err){notify(err.response?.data?.error||'Unable to update card','error')}};

  const downloadBackup=async()=>{try{const res=await api.get('/api/v3/backup/export/');const url=URL.createObjectURL(new Blob([JSON.stringify(res.data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`smart-expense-backup-${today()}.json`;a.click();URL.revokeObjectURL(url);notify('Backup downloaded')}catch{notify('Unable to create backup','error')}};
  const importBackup=async(file)=>{if(!file)return;if(!window.confirm('This will replace your current finance data with the backup. Continue?'))return;try{const data=JSON.parse(await file.text());await api.post('/api/v3/backup/import/',{data,confirm:true});notify('Backup restored');await refresh();await load()}catch(err){notify(err.response?.data?.error||'Backup restore failed','error')}};
  const importCsv=async(file)=>{if(!file)return;const body=new FormData();body.append('file',file);try{const res=await api.post('/api/v3/import/csv/',body);notify(`${res.data?.created||0} transactions imported`);await refresh();await load()}catch(err){notify(err.response?.data?.error||'CSV import failed','error')}};

  const eventRows=useMemo(()=>{
    const rows=[];(calendar.transactions||[]).forEach(x=>rows.push({date:x.date,title:x.title,meta:x.transaction_type,amount:x.amount}));(calendar.bills||[]).forEach(x=>rows.push({date:x.date,title:x.title,meta:x.is_paid?'Bill paid':'Bill due',amount:x.amount}));(calendar.transfers||[]).forEach(x=>rows.push({date:x.date,title:`${x.from_account_name} → ${x.to_account_name}`,meta:'Transfer',amount:x.amount}));(calendar.recurring||[]).forEach(x=>rows.push({date:x.next_run,title:x.title,meta:`Recurring ${x.frequency}`,amount:x.amount}));return rows.sort((a,b)=>String(a.date).localeCompare(String(b.date)));
  },[calendar]);

  const tabs=[['budgets','Budgets',WalletCards],['recurring','Recurring',Repeat2],['transfers','Transfers',ArrowRightLeft],['cards','Cards',CreditCard],['categories','Categories',Tags],['calendar','Calendar',CalendarDays],['backup','Backup',FolderUp]];
  return <div className="page-stack"><PageHeader eyebrow="PLANNER" title="Automation & planning" description="Budgets, recurring money, transfers, cards, custom categories, calendar and backup in one place." />
    <div className="segmented planner-tabs">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/>{label}</button>)}</div>
    {loading?<Surface><div className="loading-state">Loading planner…</div></Surface>:<>
      {tab==='budgets'&&<><Surface><form className="inline-form planner-form" onSubmit={createBudget}><select name="category" required>{[...new Set([...defaultCategories,...categories.map(x=>x.name)])].map(x=><option key={x}>{x}</option>)}</select><input name="amount" required type="number" min="1" step="0.01" placeholder="Monthly limit"/><button className="button primary" disabled={saving}><Plus size={16}/>Add budget</button></form></Surface><div className="planner-card-grid">{budgets.length?budgets.map(x=><Surface key={x.id} className="planner-card"><div className="planner-card-head"><div><span className="micro-label">CATEGORY BUDGET</span><h3>{x.category}</h3></div><button className="icon-button danger" onClick={()=>remove('category-budgets',x.id)}><Trash2 size={15}/></button></div><strong>{money(x.spent,symbol)} / {money(x.amount,symbol)}</strong><Progress value={x.percent}/><small>{x.percent}% used this month</small></Surface>):<Surface><EmptyState title="No category budgets" description="Create limits for food, shopping, fuel and more."/></Surface>}</div></>}
      {tab==='recurring'&&<><Surface><form className="planner-form-grid" onSubmit={createRecurring}><input name="title" required placeholder="Rent / Salary / Subscription"/><input name="amount" required type="number" min="0.01" step="0.01" placeholder="Amount"/><select name="transaction_type"><option>EXPENSE</option><option>INCOME</option><option>BILL</option></select><select name="category">{defaultCategories.map(x=><option key={x}>{x}</option>)}</select><select name="account"><option value="">No account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select name="payment_method"><option>UPI</option><option>Cash</option><option>Card</option><option>Bank Transfer</option></select><select name="frequency"><option>MONTHLY</option><option>WEEKLY</option><option>DAILY</option><option>YEARLY</option></select><input name="interval" type="number" min="1" defaultValue="1"/><input name="next_run" type="date" defaultValue={today()} required/><input name="notes" placeholder="Optional note"/><button className="button primary" disabled={saving}><Plus size={16}/>Add recurring</button></form></Surface><Surface>{recurring.length?<div className="money-list">{recurring.map(x=><div className="money-row" key={x.id}><div className="money-badge lent"><Repeat2 size={18}/></div><div className="money-main"><strong>{x.title}</strong><span>{x.transaction_type} • {x.frequency} every {x.interval} • next {x.next_run}</span></div><div className="money-amount"><strong>{money(x.amount,symbol)}</strong><span>{x.active?'ACTIVE':'PAUSED'}</span></div><button className="icon-button danger" onClick={()=>remove('recurring',x.id)}><Trash2 size={15}/></button></div>)}</div>:<EmptyState title="No recurring rules" description="Automate rent, salary, EMI and subscriptions."/>}</Surface></>}
      {tab==='transfers'&&<><Surface><form className="planner-form-grid" onSubmit={createTransfer}><select name="from_account" required><option value="">From account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select name="to_account" required><option value="">To account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input name="amount" required type="number" min="0.01" step="0.01" placeholder="Amount"/><input name="date" type="date" defaultValue={today()} required/><input name="notes" placeholder="Transfer note"/><button className="button primary" disabled={saving}><ArrowRightLeft size={16}/>Transfer</button></form></Surface><Surface>{transfers.length?<div className="money-list">{transfers.map(x=><div className="money-row" key={x.id}><div className="money-badge lent"><ArrowRightLeft size={18}/></div><div className="money-main"><strong>{x.from_account_name} → {x.to_account_name}</strong><span>{x.date} • {x.notes||'Account transfer'}</span></div><div className="money-amount"><strong>{money(x.amount,symbol)}</strong><span>TRANSFER</span></div></div>)}</div>:<EmptyState title="No transfers yet" description="Move money between your own accounts without counting it as spending."/>}</Surface></>}
      {tab==='cards'&&<><Surface><form className="planner-form-grid" onSubmit={createCard}><input name="name" required placeholder="Card name"/><input name="last4" maxLength="4" placeholder="Last 4 digits"/><input name="credit_limit" required type="number" min="0" step="0.01" placeholder="Credit limit"/><input name="outstanding" type="number" min="0" step="0.01" placeholder="Current outstanding"/><input name="statement_day" type="number" min="1" max="28" defaultValue="1"/><input name="due_day" type="number" min="1" max="28" defaultValue="20"/><select name="linked_account"><option value="">Payment account (optional)</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><button className="button primary" disabled={saving}><Plus size={16}/>Add card</button></form></Surface><div className="planner-card-grid">{cards.length?cards.map(card=><Surface className="planner-card credit-card-panel" key={card.id}><div className="planner-card-head"><div><span className="micro-label">CREDIT CARD</span><h3>{card.name} {card.last4?`•••• ${card.last4}`:''}</h3></div><button className="icon-button danger" onClick={()=>remove('credit-cards',card.id)}><Trash2 size={15}/></button></div><strong>{money(card.outstanding,symbol)} outstanding</strong><Progress value={card.utilization_percent}/><small>{card.utilization_percent}% utilization • {money(card.available_credit,symbol)} available</small><div className="planner-actions"><button className="button ghost" onClick={()=>cardActivity(card,'PURCHASE')}>Record purchase</button><button className="button primary" onClick={()=>cardActivity(card,'PAYMENT')}>Record payment</button></div></Surface>):<Surface><EmptyState title="No credit cards" description="Track limits, outstanding balance, due dates and payments."/></Surface>}</div></>}
      {tab==='categories'&&<><Surface><form className="inline-form planner-form" onSubmit={createCategory}><input name="name" required placeholder="Custom category"/><select name="category_type"><option>EXPENSE</option><option>INCOME</option></select><input name="color" type="color" defaultValue="#0A84FF"/><button className="button primary" disabled={saving}><Plus size={16}/>Add category</button></form></Surface><div className="planner-card-grid">{categories.length?categories.map(x=><Surface key={x.id} className="planner-card"><div className="planner-card-head"><div><span className="micro-label">{x.category_type}</span><h3><span className="category-color" style={{background:x.color}}/> {x.name}</h3></div><button className="icon-button danger" onClick={()=>remove('categories',x.id)}><Trash2 size={15}/></button></div></Surface>):<Surface><EmptyState title="No custom categories" description="Create categories that match your own spending style."/></Surface>}</div></>}
      {tab==='calendar'&&<><Surface><div className="section-heading"><div><span>FINANCIAL CALENDAR</span><h2>Month view</h2></div><input className="month-input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div>{eventRows.length?<div className="calendar-list">{eventRows.map((x,i)=><div className="calendar-row" key={`${x.date}-${i}`}><time>{x.date}</time><div><strong>{x.title}</strong><span>{x.meta}</span></div><b>{money(x.amount,symbol)}</b></div>)}</div>:<EmptyState title="Nothing scheduled" description="Transactions, bill due dates, transfers and recurring items appear here."/>}</Surface></>}
      {tab==='backup'&&<><Surface><div className="backup-grid"><button className="backup-action" onClick={downloadBackup}><Download size={24}/><strong>Download full backup</strong><span>JSON snapshot of accounts, transactions, bills, goals, budgets, recurring rules and cards.</span></button><button className="backup-action" onClick={()=>backupInput.current?.click()}><Upload size={24}/><strong>Restore backup</strong><span>Replace this account's finance data from a Smart Expense V3 backup.</span></button><button className="backup-action" onClick={()=>csvInput.current?.click()}><FolderUp size={24}/><strong>Import CSV</strong><span>Bulk import up to 1000 transactions using common transaction columns.</span></button></div><input ref={backupInput} type="file" accept="application/json,.json" hidden onChange={e=>{importBackup(e.target.files?.[0]);e.target.value=''}}/><input ref={csvInput} type="file" accept="text/csv,.csv" hidden onChange={e=>{importCsv(e.target.files?.[0]);e.target.value=''}}/></Surface></>}
    </>}</div>
}
