import React, { useState } from 'react';
import { ArrowRight, CheckCircle2, ShieldCheck, Sparkles } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import api from '../services/api';
import logoFull from '../assets/logo-full.png';

export default function Register(){
 const navigate=useNavigate(); const [form,setForm]=useState({name:'',email:'',phone:'',password:'',confirm:''});const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [accepted,setAccepted]=useState(false);
 const valid=form.password.length>=8&&/[A-Z]/.test(form.password)&&/[a-z]/.test(form.password)&&/\d/.test(form.password);
 const set=(k,v)=>setForm(p=>({...p,[k]:v}));
 const submit=async(e)=>{e.preventDefault();setError('');if(!valid){setError('Use 8+ characters with uppercase, lowercase and a number.');return}if(form.password!==form.confirm){setError('Passwords do not match.');return}if(!accepted){setError('Please accept the Terms and Privacy Policy.');return}setLoading(true);try{const email=form.email.trim().toLowerCase();const res=await api.post('/api/register/',{username:email,name:form.name.trim(),email,phone:form.phone.trim()?`+91${form.phone.replace(/\D/g,'').slice(-10)}`:'',password:form.password,accepted_terms:true,accepted_privacy:true});setMessage(res.data?.message||'Account created');setTimeout(()=>navigate('/login',{replace:true}),700)}catch(err){const data=err.response?.data;setError(data?.error||data?.detail||'Unable to create account.')}finally{setLoading(false)}};
 return <div className="auth-page"><div className="auth-orb one"/><div className="auth-orb two"/><section className="auth-story"><img src={logoFull} alt="Smart Expense Tracker"/><div className="auth-story-copy"><div className="eyebrow">START CLEAN</div><h1>Build a clear money habit from day one.</h1><p>Set your budget, connect your accounts, capture receipts and watch your financial picture become easier to understand.</p><div className="auth-points"><div><Sparkles size={18}/><span>Simple daily tracking</span></div><div><CheckCircle2 size={18}/><span>Goals and commitments together</span></div><div><ShieldCheck size={18}/><span>Your data stays account-scoped</span></div></div></div></section><section className="auth-panel"><form className="auth-card register-card" onSubmit={submit}><div className="auth-mobile-logo"><img src={logoFull} alt="Smart Expense Tracker"/></div><span className="micro-label">CREATE ACCOUNT</span><h2>Your finance workspace</h2><p>It takes less than a minute to get started.</p>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<div className="form-grid two"><label><span>Full name</span><input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Your name"/></label><label><span>Mobile</span><input inputMode="numeric" value={form.phone} onChange={e=>set('phone',e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit number"/></label></div><label><span>Email</span><input required type="email" value={form.email} onChange={e=>set('email',e.target.value)} placeholder="you@example.com"/></label><div className="form-grid two"><label><span>Password</span><input required type="password" value={form.password} onChange={e=>set('password',e.target.value)} placeholder="Strong password"/></label><label><span>Confirm</span><input required type="password" value={form.confirm} onChange={e=>set('confirm',e.target.value)} placeholder="Repeat password"/></label></div><div className="password-rules"><span className={form.password.length>=8?'ok':''}>8+ characters</span><span className={/[A-Z]/.test(form.password)?'ok':''}>Uppercase</span><span className={/\d/.test(form.password)?'ok':''}>Number</span></div><label className="legal-consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I agree to the <Link to="/terms">Terms of Use</Link> and <Link to="/privacy">Privacy Policy</Link>.</span></label><button className="button primary full auth-submit" disabled={loading||!accepted}>{loading?'Creating…':<>Create account <ArrowRight size={18}/></>}</button><div className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></div></form></section></div>
}
